services:
  backend:
    build: ./back
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
      - /app/node_modules
      - ./certs:/certs
    env_file:
      - ./back/.env
    networks:
      - transcendance

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    depends_on:
      - backend
    ports:
      - "3000:443"
      - "8080:80"
    volumes:
      - ./certs:/certs
    networks:
      - transcendance

networks:
  transcendance:
    name: transcendance
    driver: bridge